/*
 * Copyright (C) 2025 FastChickensHR <contact@fastchickenshr.com>
 *
 * This file is part of the FastChickensHR project.
 *
 * For license information see the LICENSE file in the root of this project.
 */
package com.fastChickensHR.edi.fakeData;

import com.fastChickensHR.edi.common.exception.ValidationException;
import com.fastChickensHR.edi.domain.Person;
import com.fastChickensHR.edi.x834.converters.EnrollmentContext;
import com.fastChickensHR.edi.x834.converters.PersonToMemberConverter;
import com.fastChickensHR.edi.x834.enrollment.SubscriberEnrollment;
import com.fastChickensHR.edi.x834.header.Header;
import com.fastChickensHR.edi.x834.loop2000.Member;
import com.fastChickensHR.edi.x834.loop2000.data.CoverageLevelCode;
import com.fastChickensHR.edi.x834.loop2000.data.IndividualRelationshipCode;
import com.fastChickensHR.edi.x834.loop2000.data.InsuranceLineCode;
import com.fastChickensHR.edi.x834.loop2000.data.MaintenanceTypeCode;
import com.fastChickensHR.edi.x834.loop2000.data.MemberIndicator;
import com.fastChickensHR.edi.x834.loop2000.loop3000.HealthCoverage;
import com.fastChickensHR.edi.x834.trailer.Trailer;
import com.fastChickensHR.edi.x834.x834Context;
import com.fastChickensHR.edi.x834.x834Document;
import net.datafaker.Faker;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Fluent generator that assembles a complete fake {@link x834Document} containing
 * a header, trailer, and a configurable number of employees with dependents.
 * <p>
 * Family structures are generated by {@link PersonGenerator} using 2020 US Census /
 * ACS-calibrated distributions by default (48 % married, children distribution of
 * 57 % / 18 % / 15 % / 10 % for 0 / 1 / 2 / 3+ children). Callers may override
 * these weights via {@link #withMarriedRate} and {@link #withChildrenWeights}.
 * <p>
 * Domain {@link Person} objects are converted to X12 834 {@link Member} records
 * via {@link PersonToMemberConverter}, ensuring the full domain→spec pipeline is
 * exercised in generated test files.
 *
 * <pre>{@code
 * x834Document doc = TestDataFaker.withSeed(1L)
 *         .document()
 *         .withEmployees(100)
 *         .build();
 * String edi = doc.generateDocument().orElseThrow();
 * }</pre>
 */
public final class DocumentGenerator {

    // 2020 ACS defaults (same as PersonGenerator)
    private static final double DEFAULT_MARRIED_RATE = 0.48;
    private static final double[] DEFAULT_CHILDREN_WEIGHTS = {0.57, 0.18, 0.15, 0.10};

    private final TestDataFaker parent;
    private final Faker faker;
    private final Random random;

    private int employeeCount = 1;
    private double marriedRate = DEFAULT_MARRIED_RATE;
    private double[] childrenWeights = DEFAULT_CHILDREN_WEIGHTS;
    private x834Context context;

    DocumentGenerator(TestDataFaker parent) {
        this.parent = parent;
        this.faker = parent.faker();
        this.random = parent.random();
    }

    /** Number of subscriber employees to include on the file. */
    public DocumentGenerator withEmployees(int count) {
        if (count < 1) throw new IllegalArgumentException("employee count must be >= 1");
        this.employeeCount = count;
        return this;
    }

    /**
     * Probability (0.0–1.0) that an employee has a spouse.
     * Defaults to 0.48 (2020 ACS married-couple household rate).
     */
    public DocumentGenerator withMarriedRate(double rate) {
        if (rate < 0.0 || rate > 1.0) throw new IllegalArgumentException("marriedRate must be in [0,1]");
        this.marriedRate = rate;
        return this;
    }

    /**
     * Children-count distribution weights for 0, 1, 2, and 3+ children.
     * Must have exactly 4 elements that sum to approximately 1.0.
     * Defaults to 2020 ACS values: {0.57, 0.18, 0.15, 0.10}.
     *
     * @deprecated Use {@link #withChildrenWeights(double[])} instead.
     */
    @Deprecated
    public DocumentGenerator withMaxChildren(int max) {
        if (max < 0) throw new IllegalArgumentException("maxChildren must be >= 0");
        // Back-compat: treat maxChildren=0 as no children, else use census defaults
        if (max == 0) {
            this.childrenWeights = new double[]{1.0, 0.0, 0.0, 0.0};
        } else {
            this.childrenWeights = DEFAULT_CHILDREN_WEIGHTS;
        }
        return this;
    }

    /**
     * Override children-count distribution weights.
     * Must have exactly 4 elements representing probabilities for 0, 1, 2, 3+ children.
     */
    public DocumentGenerator withChildrenWeights(double[] weights) {
        if (weights == null || weights.length != 4) {
            throw new IllegalArgumentException("childrenWeights must have exactly 4 elements [0,1,2,3+]");
        }
        this.childrenWeights = weights.clone();
        return this;
    }

    /**
     * @deprecated Use {@link #withMarriedRate(double)} instead. This method is
     * kept for backwards compatibility and maps directly to {@link #withMarriedRate}.
     */
    @Deprecated
    public DocumentGenerator withSpouseRate(double rate) {
        return withMarriedRate(rate);
    }

    /** Use a pre-built context instead of generating one. */
    public DocumentGenerator withContext(x834Context context) {
        this.context = context;
        return this;
    }

    /** Builds a complete {@link x834Document} populated with fake data. */
    public x834Document build() throws ValidationException {
        x834Context ctx = context != null ? context : parent.context().build();

        Header header = new Header.Builder(ctx)
                .setInterchangeControlNumber(String.format("%09d", faker.number().numberBetween(1, 999_999_999)))
                .setGroupControlNumber(ctx.getGroupControlNumber() != null ? ctx.getGroupControlNumber() : "1")
                .setTransactionSetIdentifierCode("834")
                .setTransactionSetControlNumber(ctx.getTransactionSetControlNumber() != null
                        ? ctx.getTransactionSetControlNumber() : "0001")
                .setReferenceIdentification(faker.numerify("REF#######"))
                .setMasterPolicyNumber(faker.bothify("MP-#####"))
                .setPlanSponsorName(faker.company().name())
                .setPayerName(faker.company().name())
                .build();

        Trailer trailer = new Trailer.Builder(ctx)
                .setTransactionSetControlNumber(ctx.getTransactionSetControlNumber() != null
                        ? ctx.getTransactionSetControlNumber() : "0001")
                .setGroupControlNumber(ctx.getGroupControlNumber() != null ? ctx.getGroupControlNumber() : "1")
                .build();

        x834Document.Builder builder = new x834Document.Builder(ctx)
                .withHeader(header)
                .withTrailer(trailer);

        PersonGenerator personGen = new PersonGenerator(parent)
                .withMarriedRate(marriedRate)
                .withChildrenWeights(childrenWeights);

        EnrollmentContext enrollmentCtx = EnrollmentContext.builder()
                .policyNumber(faker.bothify("MP-#####"))
                .memberIdQualifier("0F")
                .memberIndicator(MemberIndicator.INSURED)
                .maintenanceTypeCode(MaintenanceTypeCode.ADDITION)
                .enrollmentDate(LocalDateTime.now().minusDays(random.nextInt(90)))
                .coverageStartDate(LocalDateTime.now().minusDays(random.nextInt(90)))
                .build();

        for (int i = 0; i < employeeCount; i++) {
            Person person = personGen.build();
            Member member = PersonToMemberConverter.convert(person, enrollmentCtx);

            CoverageLevelCode level = deriveCoverageLevel(member);
            List<HealthCoverage> coverages = buildCoverages(level);

            SubscriberEnrollment emp = new SubscriberEnrollment(member, coverages);
            builder.addMember(emp.member());
            for (HealthCoverage hd : emp.coverages()) {
                builder.addSegment(hd);
            }
        }

        return builder.build();
    }

    private List<HealthCoverage> buildCoverages(CoverageLevelCode level) throws ValidationException {
        List<InsuranceLineCode> lines = List.of(
                InsuranceLineCode.HEALTH,
                InsuranceLineCode.DENTAL,
                InsuranceLineCode.VISION_OPTICAL);
        List<HealthCoverage> coverages = new ArrayList<>(lines.size());
        for (InsuranceLineCode line : lines) {
            coverages.add(new HealthCoverageGenerator(parent)
                    .withInsuranceLine(line)
                    .withCoverageLevel(level)
                    .build());
        }
        return coverages;
    }

    private CoverageLevelCode deriveCoverageLevel(Member member) {
        boolean hasSpouse = member.getDependents().stream()
                .anyMatch(d -> d.getRelationshipCode() == IndividualRelationshipCode.SPOUSE);
        boolean hasChildren = member.getDependents().stream()
                .anyMatch(d -> d.getRelationshipCode() == IndividualRelationshipCode.CHILD);
        if (hasSpouse && hasChildren) return CoverageLevelCode.FAMILY;
        if (hasSpouse) return CoverageLevelCode.EMPLOYEE_AND_SPOUSE;
        if (hasChildren) return CoverageLevelCode.EMPLOYEE_AND_CHILDREN;
        return CoverageLevelCode.EMPLOYEE_ONLY;
    }
}
